# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
addons:
  apt_packages:
    - liblapack-dev
    - libopenblas-dev
after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("DSDP")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
